name: Redis Demo CI

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Flask
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASSWORD: 123456
        run: |
          python app.py &
          sleep 5

      - name: Run Tests
        run: |
          python test.py
